"""
Survey data export utilities
Converts survey data to various cave survey formats
"""
from typing import List, Dict, Any
import csv
import json
from io import StringIO


def convert_to_walls_srv(shots: List[Dict[str, Any]], survey_name: str = "Survey") -> str:
    """
    Convert shots to Walls .srv format

    Format:
    #Fix <station> <east> <north> <elevation>
    <from> <to> <distance> <azimuth> <inclination>
    """
    lines = [
        f"; Walls Survey File: {survey_name}",
        f"; Generated by Cave Survey Tool",
        f"#Units Feet Degrees",
        f"#Survey Name={survey_name}",
        ""
    ]

    for shot in shots:
        if shot.get('type') == 'survey':  # Only centerline shots
            from_station = shot.get('from', '').replace('@', '_')
            to_station = shot.get('to', '').replace('@', '_')
            distance = shot.get('distance', 0)
            azimuth = shot.get('compass', 0)
            inclination = shot.get('clino', 0)

            # Walls format: FROM TO DISTANCE AZIMUTH INCLINATION
            lines.append(f"{from_station}\t{to_station}\t{distance:.2f}\t{azimuth:.1f}\t{inclination:.1f}")

    return "\n".join(lines)


def convert_to_compass_dat(shots: List[Dict[str, Any]], survey_name: str = "Survey") -> str:
    """
    Convert shots to Compass .dat format

    Format is more complex with headers and multiple sections
    """
    lines = [
        f"{survey_name}",
        f"SURVEY NAME: {survey_name}",
        f"SURVEY DATE: ",
        f"COMMENT:",
        f"DECLINATION: 0.00  FORMAT: DDDDUDRLAD  CORRECTIONS: 0.00 0.00 0.00",
        ""
    ]

    for shot in shots:
        if shot.get('type') == 'survey':
            from_station = shot.get('from', '')[:12].ljust(12)
            to_station = shot.get('to', '')[:12].ljust(12)
            distance = shot.get('distance', 0)
            azimuth = shot.get('compass', 0)
            inclination = shot.get('clino', 0)

            # Compass format: FROM TO LENGTH BEARING INC LEFT UP DOWN RIGHT
            line = f"{from_station}{to_station}{distance:6.1f}{azimuth:6.1f}{inclination:6.1f}"
            line += f"{0:6.1f}{0:6.1f}{0:6.1f}{0:6.1f}  #|"
            lines.append(line)

    lines.append("\f")  # Form feed
    return "\n".join(lines)


def convert_to_survex_svx(shots: List[Dict[str, Any]], survey_name: str = "Survey") -> str:
    """
    Convert shots to Survex .svx format

    Survex is a common format for cave survey processing
    """
    lines = [
        f"; Survex Survey File: {survey_name}",
        f"; Generated by Cave Survey Tool",
        "",
        f"*begin {survey_name}",
        "*units tape feet",
        "*units compass degrees",
        "*units clino degrees",
        "*data normal from to tape compass clino",
        ""
    ]

    for shot in shots:
        if shot.get('type') == 'survey':
            from_station = shot.get('from', '').replace('@', '_')
            to_station = shot.get('to', '').replace('@', '_')
            distance = shot.get('distance', 0)
            azimuth = shot.get('compass', 0)
            inclination = shot.get('clino', 0)

            lines.append(f"{from_station}\t{to_station}\t{distance:.2f}\t{azimuth:.1f}\t{inclination:.1f}")

    lines.append("")
    lines.append(f"*end {survey_name}")

    return "\n".join(lines)


def convert_to_therion_th(shots: List[Dict[str, Any]], survey_name: str = "Survey") -> str:
    """
    Convert shots to Therion .th format

    Therion is used for cave mapping and drawing
    """
    lines = [
        f"survey {survey_name} -title \"{survey_name}\"",
        "",
        "  units length feet",
        "  units compass degrees",
        "  units clino degrees",
        "",
        "  data normal from to length compass clino",
        ""
    ]

    for shot in shots:
        if shot.get('type') == 'survey':
            from_station = shot.get('from', '').replace('@', '_')
            to_station = shot.get('to', '').replace('@', '_')
            distance = shot.get('distance', 0)
            azimuth = shot.get('compass', 0)
            inclination = shot.get('clino', 0)

            lines.append(f"    {from_station}\t{to_station}\t{distance:.2f}\t{azimuth:.1f}\t{inclination:.1f}")

    lines.append("")
    lines.append("endsurvey")

    return "\n".join(lines)


def convert_to_csv(shots: List[Dict[str, Any]]) -> str:
    """
    Convert shots to simple CSV format
    """
    output = StringIO()
    writer = csv.writer(output)

    # Header
    writer.writerow(['from', 'to', 'distance', 'compass', 'clino', 'type'])

    # Data
    for shot in shots:
        writer.writerow([
            shot.get('from', ''),
            shot.get('to', ''),
            shot.get('distance', 0),
            shot.get('compass', 0),
            shot.get('clino', 0),
            shot.get('type', 'survey')
        ])

    return output.getvalue()


def convert_to_json(shots: List[Dict[str, Any]], metadata: Dict[str, Any] = None) -> str:
    """
    Convert to JSON format with metadata
    """
    data = {
        "metadata": metadata or {},
        "shots": shots
    }
    return json.dumps(data, indent=2)


def get_survey_shots_from_drafts(drafts: List[Any]) -> List[Dict[str, Any]]:
    """
    Extract all shots from committed drafts
    Combines multiple drafts into single shot list
    """
    all_shots = []

    for draft in drafts:
        if draft.status == 'committed' and draft.draft_data:
            shots = draft.draft_data.get('shots', [])
            for shot in shots:
                # Add draft metadata
                shot_copy = shot.copy()
                shot_copy['draft_id'] = draft.id
                shot_copy['source_filename'] = draft.original_filename
                all_shots.append(shot_copy)

    return all_shots


def format_export_filename(survey_name: str, format_ext: str) -> str:
    """
    Generate clean filename for export
    """
    # Clean survey name
    clean_name = "".join(c if c.isalnum() or c in ('-', '_') else '_' for c in survey_name)
    return f"{clean_name}.{format_ext}"
